/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import TabladeSimbolos.ReporteTabla;
import arbol.Errores.ErroSemantico.ListaErrores;
import arbol.Expresion;
import arbol.Funciones.TabladeFunciones;
import arbol.Instruccion;
import arbol.Nodo;
import arbol.Simbolo;
import arbol.TablaDeSimbolos;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author obatres_
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    
    public static String consola="";
    public static String errores="";
    public String cadenadeArbol="";
    public static TabladeFunciones tf = new TabladeFunciones();
    public static ArrayList<ReporteTabla> RTS = new ArrayList<>();
    public static int ambito=0;
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoDeEntrada = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoSalida = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextoErrores = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        AbrirArchivo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        EjecutaJfelxCup = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        EjecutaJfelxCup1 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        EjecutaJfelxCup2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem2.setText("jMenuItem2");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(TextoDeEntrada);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        TextoSalida.setEditable(false);
        TextoSalida.setBackground(new java.awt.Color(255, 255, 255));
        TextoSalida.setSelectedTextColor(new java.awt.Color(51, 153, 0));
        jScrollPane2.setViewportView(TextoSalida);

        jLabel1.setText("Salida:");

        jLabel2.setText("Entrada:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("ARIT IDE");

        TextoErrores.setEditable(false);
        TextoErrores.setBackground(new java.awt.Color(255, 255, 255));
        TextoErrores.setSelectedTextColor(new java.awt.Color(51, 153, 0));
        jScrollPane3.setViewportView(TextoErrores);

        jLabel4.setText("Errores:");

        jMenu2.setText("Archivo");

        AbrirArchivo.setText("Abrir");
        AbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirArchivoActionPerformed(evt);
            }
        });
        jMenu2.add(AbrirArchivo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ejecutar");

        EjecutaJfelxCup.setText("Jflex/CUP");
        EjecutaJfelxCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutaJfelxCupActionPerformed(evt);
            }
        });
        jMenu3.add(EjecutaJfelxCup);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Graficar");

        EjecutaJfelxCup1.setText("Jflex/CUP");
        EjecutaJfelxCup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutaJfelxCup1ActionPerformed(evt);
            }
        });
        jMenu8.add(EjecutaJfelxCup1);

        jMenuBar1.add(jMenu8);

        jMenu11.setText("TS");

        EjecutaJfelxCup2.setText("VerTablaDeSimbolos");
        EjecutaJfelxCup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutaJfelxCup2ActionPerformed(evt);
            }
        });
        jMenu11.add(EjecutaJfelxCup2);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void interpretar() {
        analizadores.Sintactico pars;
        LinkedList<Nodo> AST_arbolSintaxisAbstracta = null;
        String consola=null;
        try {
            pars=new analizadores.Sintactico(new analizadores.Lexico(new StringReader(TextoDeEntrada.getText())));
            pars.parse();      
            AST_arbolSintaxisAbstracta = pars.getAST();
        } catch (Exception ex) {
            System.out.println("Error fatal en compilación de entrada.");
            System.out.println("Causa: "+ex.getCause());
        } 
        DibujarArbol(AST_arbolSintaxisAbstracta);
        ejecutarAST(AST_arbolSintaxisAbstracta);
        
    }
    
            /**
     * Recibe una lista de instrucciones y la ejecuta
     * @param ast lista de instrucciones
     */
    public void ejecutarAST(LinkedList<Nodo> ast) {
        if(ast==null){
            System.out.println("No es posible ejecutar las instrucciones porque\r\n"
                    + "el árbol no fue cargado de forma adecuada por la existencia\r\n"
                    + "de errores léxicos o sintácticos.");
            return;
        }
        //Se crea una tabla de símbolos global para ejecutar las instrucciones.
        TablaDeSimbolos ts=new TablaDeSimbolos();
        //Se ejecuta cada instruccion en el ast, es decir, cada instruccion de 
        //la lista principal de instrucciones.
        for(Nodo ins:ast){
            //Si existe un error léxico o sintáctico en cierta instrucción esta
            //será inválida y se cargará como null, por lo tanto no deberá ejecutarse
            //es por esto que se hace esta validación.
            if(ins!=null)
                if(ins instanceof Expresion)//Para todas las instacias de la clase Expresion se ejecuta el metodo "ejecutar()" 
                {                           //que recibe como parametro la tabla de simbolos de la misma instancia dentro del arbol
                    ((Expresion)ins).ejecutar(ts); //y devuelve valores de operaciones aritmeticas y logicas
                }else if(ins instanceof Instruccion)
                {                           //Para todas las instancias de la clase Instruccion se ejecuta el metodo "ejecutar()"
                    ((Instruccion)ins).ejecutar(ts);//que recibe como parametro la tabla de simbolos de la misma instancia dentro del arbol
                }else{                              //y devuelve la ejecucion de instrucciones como condicionales o ciclos
                    System.out.println("Error al ejecutar un nivel en el arbol AST");  //reportar error
                }
        this.TextoSalida.setText(consola+"\n");
        
        }
    }
    
    private void AbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirArchivoActionPerformed
        JFileChooser jf= new JFileChooser();
        jf.setFileSelectionMode( JFileChooser.FILES_ONLY );
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto (*.arit)", "arit");
        jf.setFileFilter(filtro);
        int seleccion = jf.showOpenDialog(this);
        if(seleccion == JFileChooser.APPROVE_OPTION )
        {       
            try {
                BufferedReader bufferreader;                 
                File file = jf.getSelectedFile();
                bufferreader = new BufferedReader(new FileReader(file.getAbsolutePath()));  
                String linea, contenido= "";
                
                //leeendo linea a linea
                while ((linea = bufferreader.readLine())!=null)
                {
                    contenido += linea +"\n";
                }
                            
                //Agregando texto al editor
                this.TextoDeEntrada.setText(contenido);                
                bufferreader.close();
            } 
            catch (IOException ex) 
            {Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);}
        }
    }//GEN-LAST:event_AbrirArchivoActionPerformed

    private void EjecutaJfelxCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutaJfelxCupActionPerformed
        proyectocupjlexwindows.ProyectoCupJlexWindows.tf.clear();
        RTS.clear();
        this.TextoSalida.setText("");
        consola="";
        errores="";
        interpretar();
        ListaErrores.VerErrores();
        this.TextoErrores.setText(errores+"\n");
    }//GEN-LAST:event_EjecutaJfelxCupActionPerformed

    public  void DibujarArbol (LinkedList<Nodo> arbol){
        StringBuilder builder = new StringBuilder();
        int cont = 1;
        String root = "nodo" + cont;
        builder.append("digraph lab5 {\n");
        builder.append(root).append(" [label=\"ARIT\"];\n");
        
        for (Nodo nodo : arbol) {
                cont = nodo.Dibujar(builder, root, cont);
        }
        builder.append("}");
        
        //System.out.println(builder.toString());
        cadenadeArbol=builder.toString();
        
    }

    private void armar_Cuerpo_dot(String ruta_dot)
    {
        this.creararchivo(ruta_dot, cadenadeArbol);
    }
    public void GraficarArbol(){
        String ruta_dot = System.getProperty("user.home") + File.separator +"SalidasDot"+File.separator+"ast.dot"; 
        String ruta_png = System.getProperty("user.home") + File.separator +"SalidasDot"+File.separator+"ast.png"; 
        this.armar_Cuerpo_dot(ruta_dot);
        this.crearGrafo(ruta_dot, ruta_png);
        this.autoAbrir(ruta_png); 
    }
       
    private void autoAbrir(String ruta)
    {
        try
        {
            File archivo = new File(ruta);
            if(archivo.exists())
            {
                Desktop.getDesktop().open(archivo);
            }
        }
        catch (IOException ex) 
        {
        }
    }
    
    private void crearGrafo(String ruta_dot, String ruta_png)
    {
        String tParam = "-Tpng";    
        String tOParam = "-o";        
        
        String[] cmd = new String[5]; 
        
        cmd[0] = "dot.exe";
        cmd[1] = tParam;    
        cmd[2] = ruta_dot;
        cmd[3] = tOParam;   
        cmd[4] = ruta_png;
        Runtime rt = Runtime.getRuntime();
        
        try 
        {
            //Hace la llamada al sistema y ejecuta la variable cmd
            rt.exec( cmd );                                    
        } 
        catch (IOException ex) 
        {
        }
    }
    public synchronized void creararchivo(String pfichero,String pcontenido){   
        FileWriter archivo = null;
   
        try{
            archivo = new FileWriter(pfichero);} 
        catch (IOException ex) 
        {
        }

        File a = new File(pfichero);        
        if (!a.exists()){return;}   
        
        try(PrintWriter printwriter = new PrintWriter(archivo)) 
        {
            printwriter.print(pcontenido);
            printwriter.close();
        }
    }
    private void EjecutaJfelxCup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutaJfelxCup1ActionPerformed
        GraficarArbol();
        
    }//GEN-LAST:event_EjecutaJfelxCup1ActionPerformed

    private void EjecutaJfelxCup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutaJfelxCup2ActionPerformed
        // TODO add your handling code here:
        String t="";
        for (ReporteTabla funcion :RTS) {
            for (Simbolo simbolo : funcion.getTabla()) {
                System.out.println("id: "+simbolo.getId()+" Valor: "+simbolo.getValor()+" Tipo:"+simbolo.getT()+" ambito:"+funcion.getAmbito());
                t+="id: "+simbolo.getId()+" Valor: "+simbolo.getValor()+" Tipo:"+simbolo.getT().tp+" ambito:"+funcion.getAmbito()+"\n";
            }
            t+="\n";
            System.out.println("\n");
        }
        JFrame j = new JFrame("TablaDeSimbolos");
        JTextPane jp = new JTextPane();
        
        jp.setText(t);
        j.add(jp);
        j.setVisible(true);
        
    }//GEN-LAST:event_EjecutaJfelxCup2ActionPerformed

    
  
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirArchivo;
    private javax.swing.JMenuItem EjecutaJfelxCup;
    private javax.swing.JMenuItem EjecutaJfelxCup1;
    private javax.swing.JMenuItem EjecutaJfelxCup2;
    private javax.swing.JEditorPane TextoDeEntrada;
    private javax.swing.JTextPane TextoErrores;
    private javax.swing.JTextPane TextoSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
