
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 10;
  public static final int CADENA = 15;
  public static final int IGUAL = 20;
  public static final int DECIMAL = 14;
  public static final int DIVIDIDO = 12;
  public static final int REVALUAR = 17;
  public static final int PARIZQ = 3;
  public static final int POTENCIA = 7;
  public static final int PARDER = 4;
  public static final int MODULO = 8;
  public static final int UMENOS = 16;
  public static final int POR = 11;
  public static final int ENTEROT = 21;
  public static final int EOF = 0;
  public static final int CADENAT = 22;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 19;
  public static final int CORIZQ = 5;
  public static final int ENTERO = 13;
  public static final int CORDER = 6;
  public static final int MAS = 9;
  public static final int RDECLARA = 18;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "POTENCIA",
  "MODULO",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "REVALUAR",
  "RDECLARA",
  "IDENTIFICADOR",
  "IGUAL",
  "ENTEROT",
  "CADENAT"
  };
}

