
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION = 27;
  public static final int RDECLARA = 38;
  public static final int POR = 13;
  public static final int IGUALD = 15;
  public static final int ENTERO = 33;
  public static final int CASE = 22;
  public static final int LLAVEDER = 8;
  public static final int CADENAT = 42;
  public static final int IDENTIFICADOR = 39;
  public static final int NOT = 26;
  public static final int MENORIGUAL = 19;
  public static final int AND = 24;
  public static final int IGUAL = 40;
  public static final int CORDER = 6;
  public static final int DIVIDIDO = 14;
  public static final int OR = 25;
  public static final int UMENOS = 36;
  public static final int IF = 29;
  public static final int REVALUAR = 37;
  public static final int MAYORIGUAL = 18;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 34;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int CADENA = 35;
  public static final int MODULO = 10;
  public static final int MENOS = 12;
  public static final int MENOR = 17;
  public static final int ENTEROT = 41;
  public static final int BREAK = 23;
  public static final int DESIGUAL = 20;
  public static final int SWITCH = 21;
  public static final int MAYOR = 16;
  public static final int POTENCIA = 9;
  public static final int ELSE = 32;
  public static final int LLAVEIZQ = 7;
  public static final int DOSP = 28;
  public static final int PTCOMA = 2;
  public static final int FALSE = 31;
  public static final int PARDER = 4;
  public static final int CORIZQ = 5;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "POTENCIA",
  "MODULO",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "IGUALD",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "DESIGUAL",
  "SWITCH",
  "CASE",
  "BREAK",
  "AND",
  "OR",
  "NOT",
  "INTERROGACION",
  "DOSP",
  "IF",
  "TRUE",
  "FALSE",
  "ELSE",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "REVALUAR",
  "RDECLARA",
  "IDENTIFICADOR",
  "IGUAL",
  "ENTEROT",
  "CADENAT"
  };
}

